### ISSUE TITLE
instantiate DPKG_MAINTSCRIPT_* variables

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-batch#1]
The bindings of the environment variables DPKG_MAINTSCRIPT_* should be passed to the symbolic execution engine as far as they can be known. In particular we need

 * DPKG_MAINTSCRIPT_NAME (which can preinst,postints,prerm,postrm)
 * DPKG_MAINTSCRIPT_PACKAGE (the name of the package "owning" the script)

see dpkg(1) for a complete list

**Comment by Niols** [comment]
this has now been done little while by the tool. closing.
